### ISSUE TITLE
Support for "Replace order rows"

### ISSUE THREAD

**Issue by oskar-wikinggruppen** [sveawebpay/php-checkout#2]
You should add support for [Replace order rows](https://paymentadminapi.svea.com/documentation/#/?id=replace-order-rows) - probably in [CheckoutAdminClient](https://github.com/sveawebpay/php-checkout/blob/master/src/CheckoutAdminClient.php)

**Comment by Marwzoor** [comment]
Hi Oskar,

We're adding support for "Replace order rows" in the upcoming release of the package.

**Comment by Marwzoor** [comment]
Fixed in release 1.3.0.
